# Generated by Django 4.2.7 on 2023-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_extruder_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='word_documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_content', models.BinaryField()),
            ],
        ),
    ]
